-- +goose Up
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS google_place_id TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS reviews_count INT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS external_raw JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS uq_clinics_url ON clinics (url) WHERE url IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_clinics_google_place_id ON clinics (google_place_id) WHERE google_place_id IS NOT NULL;

-- +goose Down
DROP INDEX IF EXISTS uq_clinics_google_place_id;
DROP INDEX IF EXISTS uq_clinics_url;
ALTER TABLE clinics DROP COLUMN IF EXISTS external_raw;
ALTER TABLE clinics DROP COLUMN IF EXISTS reviews_count;
ALTER TABLE clinics DROP COLUMN IF EXISTS rating;
ALTER TABLE clinics DROP COLUMN IF EXISTS lng;
ALTER TABLE clinics DROP COLUMN IF EXISTS lat;
ALTER TABLE clinics DROP COLUMN IF EXISTS google_place_id;
ALTER TABLE clinics DROP COLUMN IF EXISTS url;
